CREATE TABLE BANKACCOUNT 
(
  ACCOUNTID NUMBER(10, 0) NOT NULL 
, ACCOUNTNAME VARCHAR2(255 BYTE) NOT NULL 
, USERID NUMBER(10, 0) NOT NULL 
, FUNDS NUMBER(10, 2) DEFAULT 0 NOT NULL 
, CONSTRAINT SYS_C005184 PRIMARY KEY 
  (
    ACCOUNTID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C005184 ON BANKACCOUNT (ACCOUNTID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE BANKACCOUNT
ADD CONSTRAINT SYS_C005185 FOREIGN KEY
(
  USERID 
)
REFERENCES USERS
(
  USERID 
)
ENABLE;
